name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch:
          - x64
          - armv7
          - aarch64
        go:
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'
          - '1.24'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '${{ matrix.go }}'

      - name: 'Build'
        if: ${{ matrix.arch == 'x64' }}
        run: go build -v ./...

      - name: 'Test'
        if: ${{ matrix.arch == 'x64' }}
        run: go test -v ./...

      - name: 'TestRace'
        if: ${{ matrix.arch == 'x64' }}
        run: go test -race -v ./...

      - name: 'Bench'
        if: ${{ matrix.arch == 'x64' }}
        run: go test -run=- -bench=. -benchtime=1x -v ./...

      - name: 'BenchRace'
        if: ${{ matrix.arch == 'x64' }}
        run: go test -run=- -bench=. -benchtime=1x -race -v ./...

      - name: 'Vet'
        if: ${{ matrix.arch == 'x64' }}
        # -unsafeptr=false is needed because of the noescape function in bigint.go.
        run: go vet -unsafeptr=false ./...

      - name: 'Staticcheck'
        # staticcheck 2025.1.1 requires go1.23.
        if: ${{ matrix.arch == 'x64' && matrix.go >= '1.23' }}
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@2025.1.1
          staticcheck ./...

      - name: 'GCAssert'
        # Only run gcassert on the latest versions of Go. Inlining heuristics
        # change from version to version.
        # gcassert@7b67d223 uses x/tools v0.17.0, which doesn't support Go 1.24+.
        if: ${{ matrix.arch == 'x64' && matrix.go >= '1.22' && matrix.go < '1.24' }}
        run: |
          go install github.com/jordanlewis/gcassert/cmd/gcassert@7b67d223
          gcassert ./...

      - name: 'BuildTest for armv7'
        if: ${{ matrix.arch == 'armv7' }}
        env:
          GOARCH: arm
          GOARM: 7
        run: go test -c ./...

      - name: 'BuildTest for aarch64'
        if: ${{ matrix.arch == 'aarch64' }}
        env:
          GOARCH: arm64
        run: go test -c ./...

      - name: 'Test and Bench on ${{ matrix.arch }}'
        if: ${{ matrix.arch != 'x64' }}
        uses: uraimo/run-on-arch-action@v3
        with:
          arch: ${{ matrix.arch }}
          distro: ubuntu24.04
          dockerRunArgs: --mount type=bind,source="$(pwd)",target=/checkout,readonly
          run: |
            find /checkout -name '*.test' -type f -executable -print0 | xargs -0 -I '{}' sh -c '{} -test.run=. -test.bench=. -test.benchtime=1x -test.v'
