name: Go

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go:
          - '1.13'
          - '1.14'
          - '1.15'
          - '1.16'
          - '1.17'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '${{ matrix.go }}'

      - name: 'Build'
        run: go build -v ./...

      - name: 'Test'
        run: go test -v ./...

      - name: 'TestRace'
        run: go test -race -v ./...

      - name: 'Bench'
        run: go test -run=- -bench=. -benchtime=1x -v ./...

      - name: 'BenchRace'
        run: go test -run=- -bench=. -benchtime=1x -race -v ./...

      - name: 'Vet'
        # -unsafeptr=false is needed because of the noescape function in bigint.go.
        run: go vet -unsafeptr=false ./...

      - name: 'Staticcheck'
        # staticcheck requires go1.14.
        if: ${{ matrix.go != '1.13' }}
        run: |
          go get honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...
